# Auction plugin by SainttX
per-world-auctions: false
tell-other-worlds-auction-start: true

log-auctions: false
allow-autowin: true
allow-creative: false

minimum-bid-increment: 1
auction-time: 30
auction-start-fee: 1
auction-tax-percentage: 0