# Auction plugin by SainttX
log-auctions: false
allow-autowin: true
allow-cancel: true
allow-creative: false

time-between-bidding: 0
minimum-bid-increment: 1
auction-time: 30
auction-start-fee: 1
auction-tax-percentage: 0
default-auction-startprice: 100
