name: Auction
version: 0.0.2
description: An auctioning plugin
author: SainttX

main: me.sainttx.Auction
depend: [Vault]

commands:
  auction:
    description: All commands for Auction
    aliases: [auc]
  bid:
    description: Bid on an ongoing auction