#################################
#            Auction            #
#            SainttX            #
#################################

# Configuration options for various plugin integration
# settings can be defined in this section. Each integration
# option has an enable option that tells the plugin whether
# or not the option should be used. These integrated plugins
# are essentially the same things as 'chatSettings.groups'
# and stack with any defined chat setting groups.
integration:
  # Herochat plugin integration options
  # Find the plugin here: http://dev.bukkit.org/bukkit-plugins/herochat/
  herochat:
    enable: false
    # Defines your Herochat chat channel that players must be joined
    # to receive messages from the auction plugin. Messages that
    # are only sent to a single player ignore this and will send no
    # matter what.
    channel: "auction"

# Configuration options for various chat group and handler features
# are defined in this section. As the plugin expands, more options
# will be added to this section.
chatSettings:
  # Configure which plugin groups view messages. All groups stack with
  # each other so players from multiple groups can be defined to view
  # messages
  groups:
    # 'global' is the standard broadcast group, this groups recipients
    # is all players online.
    global: true
  # The handler is the delivery mechanism for which messages get
  # delivered too. Current options are: TEXT, ACTION_BAR.
  handler: TEXT

# Configuration options for various settings specific to auctions
# ie. times, bid increments, etc.
auctionSettings:
  # How much money users will be charged to start an auction.
  # If a user doesn't have enough money, they will be unable
  # to create an auction. Default: 0.
  startFee: 0
  # The percentage of the winning amount to be removed from
  # the servers economy. For example, if a user wins an auction for
  # $1K and the tax is at 30%, $300 will be removed and the owner
  # of the auction will only be given $700 as a result. Default: 0.
  taxPercent: 0
  # The start time for all auctions. There is currently no
  # way to specify how long your auction should last through commands
  # and as such all auctions will have a duration of this time. This
  # time is configured in seconds and is translated through a utility
  # class to English. For example, if the time is set to 600, the
  # formatter will output '10 minutes'. Default: 30.
  startTime: 30
  # The delay between all auctions in seconds. This is the time
  # between when an auction ends and when a new auction from the queue
  # is started. Auctions that are created within the delay are
  # automatically added to the queue. Default: 5.
  delayBetween: 5
  # The default bid increment to be used when a user doesn't specify
  # their bid increment through commands. For example, if a user types
  # /auction start 1 100, the bid increment will default to this
  # amount. Default: 50.
  defaultBidIncrement: 50
  # The minimum bid increment that is allowed to be specified. Users
  # who attempt to create an auction with an increment that is less
  # than this amount will be denied. Default: 10
  minimumBidIncrement: 10
  # The maximum bid increment that is allowed to be specified. Users
  # who attempt to create an auction with an increment that is greater
  # than this amount will be denied. Default: 9999
  maximumBidIncrement: 9999
  # The minimum amount that is allowed to be defined as an auction start
  # price. Users that attempt to create an auction that fail to meet
  # this criteria will be denied. Default: 0.
  minimumStartPrice: 0
  # The maximum amount that is allowed to be defined as an auction start
  # price. Default: 99999.
  maximumStartPrice: 99999
  # Whether or not players can auction items that have been named through
  # a plugin or anvil. Default: true.
  canAuctionNamedItems: true
  # Whether or not players can auction items that have any durability loss.
  # Default: true.
  canAuctionDamagedItems: true
  # Whether or not players can specify an autowin amount in their auction.
  # If users specify an autowin and this is set to false, they will be
  # denied the creation of the auction. Default: true.
  canSpecifyAutowin: true
  # Whether or not players can auction while in creative mode. Default: false.
  canAuctionInCreative: false
  # Whether or not players can use the /bid command with no arguments. If
  # this is set to true, players can type "/bid" and automatically increment
  # the auction with the auctions bid increment. When set to false, players
  # will be required to specify a bid amount. Default: true.
  canBidAutomatically: true
  # The maximum amount of auctions that are allowed inside an auction. Users
  # who attempt to create auctions when the queue is full will be denied.
  # Default: 3.
  auctionQueueLimit: 3
  # Defines the last time, in seconds, that users are allowed to use
  # the "/auction cancel" command. If an auctions time is less than
  # what is defined here, users will not be able to cancel their auction
  # anymore. Default: 15.
  mustCancelBefore: 15
  # Various settings regarding auction anti sniping can be defined here.
  antiSnipe:
    # Whether or not anti sniping is enabled. Default: true.
    enable: true
    # The time left, in seconds, in an auction that anti-snipe can
    # be enabled at. For example, if set to 3 and a player places a bid
    # at 2 seconds, anti-snipe will trigger if enabled and add
    # 'auctionSettings.antiSnipe.addSeconds' seconds to the auction time.
    # Default: 3.
    timeThreshold: 3
    # The maximum amount of times an auction can be sniped, this is
    # primarily to prevent auctions for going on for indefinite
    # amount of times. Default: 3.
    maxPerAuction: 3
    # The amount of seconds to add whenever an auction is sniped.
    # Default: 5.
    addSeconds: 5

# Various settings unrelated to auction specific options are found in this
# section.
general:
  # Whether or not to shorten times that are formatted through the utility
  # class. For example, this is the difference between times being shown as
  # "5 minutes 5 seconds" vs. "5m, 5s". Default: false.
  shortenedTimeFormat: false
  # A list of worlds that the auction plugin is disabled in. World names
  # are all case sensitive.
  disabledWorlds:
  - "testworld"
  # Various settings settings to block commands found in 'general.blockedCommands'
  # on specific occasions.
  blockCommands:
    # This option will block commands when players are the auction owner.
    # Default: false.
    ifAuctioning: false
    # This option will block commands when players have an auction in the
    # queue. Default: false.
    ifQueued: false
    # This option will block commands when players are the top bidder.
    # Default: false.
    ifTopBidder: false
  # A list of commands that are blocked if any of the settings in
  # 'general.blockCommands.*' are set to true. Commands here should
  # be defined as the players type them. For example, if a player
  # types /test hello, it will match the command '/test'. Keep in
  # mind that all commands are formatted to be all lower cases, so
  # commands entered here should be in all lower case.
  blockedCommands:
  - "/test"
  # A list of Bukkit Materials that are not allowed to be auctioned.
  # Valid materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  blockedMaterials:
  - "BEDROCK"
  # A list of lores that are not allowed to be present inside any
  # lore strings on an item. For example, if we have "A string of
  # lore" defined in this list (default) and an item contains
  # the lore strings "hello", "this is lore", and "lol A string of
  # lore" the item will not be allowed to go into auction due to
  # the fact that "A string of lore" is present in the third line.
  blockedLore:
  - "A string of lore"
  # A list of times that the plugin will broadcast the amount
  # of time left in the auction. The format of this list can
  # be specified as it currently is ("["#", "#"]") or as above.
  broadcastTimes: ["60", "30", "10", "3", "2", "1"]

# Every message that is sent from the plugin is found in this section.
# The message keys are made to be as intuitive as possible so that
# you don't have much difficulty with figuring out what each message does.
# All messages are formatted for chat colors regardless if there are
# placeholder present or not.
messages:
  # All messages under 'auctionFormattable' mean that messages sent
  # that are from here are first parsed with the current active auction.
  # There are various placeholders that you can insert into these messages
  # that will be formatted will information from the current auctions
  # information. These placeholders are as follows:
  # [itemamount]    - placeholder for the amount inside the reward/item
  # [time]          - placeholder for the formatted time left (ie. 30 seconds)
  # [autowin]       - placeholder for the autowin balance in the auction
  # [ownername]     - placeholder for the name of the auctions owner. defaults to "Console" if null.
  # [topbiddername] - placeholder for the name of the auctions top bidder. defaults to "Console" if null.
  # [increment]     - placeholder for the minimum increment inside an auction
  # [topbid]        - placeholder for the current top bid in the auction (untaxed)
  # [taxpercent]    - placeholder for the current tax percent set by 'auctionSettings.taxPercent'
  # [taxamount]     - placeholder for the current amount of money deducted by the tax
  # [winnings]      - placeholder for the resulting amount of money that will be won (after tax is deducted)
  # SPECIFIC MESSAGES ONLY:
  # [itemName]  - only works with itemFormat
  # [snipetime] - only works with antiSnipeAdd
  # [queuepos]  - only works with queuePosition
  #
  # Notes: - [ownername] and [topbiddername] will default to "Console" (w/o brackets)
  #          if there is no valid player entity in those placeholder slots.
  auctionFormattable:
    # The itemFormat is essentially the way [item] will be formatted inside
    # auction messages. For example, if you have a message that contains
    # "Hello [item]!", the [item] placeholder will be replaced with the items
    # name formatted as seen in itemFormat.
    itemFormat: "&c[itemName]"
    timer: "&6The auction for &c[itemamount] [item] &6has &c[time] &6remaining"
    increment: "&6The &cbidding increment &6has been set to &c$[increment]"
    info: "&c[ownername] &6is auctioning &c[itemamount] [item] &6for &c$[topbid]"
    autowin:  "&6The host has set the autowin amount to &c$[autowin]"
    start: "&c[ownername] &6started an auction for &c[itemamount] [item]"
    price: "&6The &cauction &6begins at &c$[topbid] &6and will last for &c[time]"
    cancelled: "&6The auction for [item] &6was &ccancelled"
    endByAutowin: "&6The auction for [item] ended with &c[topbiddername] &6bidding &c$[topbid] &c&n(autowin)"
    endNoBid: "&6The auction for &c[itemamount] [item] &6ended with no bids"
    end: "&c[topbiddername] &6won &c[itemamount] [item] &6with a bid of &c$[topbid]"
    endNotifyOwner: "&6Your auction has ended. Received &c$[winnings]"
    endTax: "&6A tax of &c[taxpercent]% ($[taxamount]) &6was charged"
    winner: "&6You won &c[itemamount] [item] &6with a bid of &c$[topbid]"
    bid: "&c[topbiddername] &6has bid &c$[topbid] &6on &c[itemamount] [item]"
    antiSnipeAdd: "&6ANTI-SNIPE &e- &c[snipetime] &6seconds have been added to the auction!"
    queuePosition: "&6Your auction is &c#[queuepos] &6in the auction queue"
  # Error messages are messages sent to players whenever they have failed
  # to define something correctly in their commands, or in other instances
  # like if they are lacking permissions to a command, etc.
  error:
    insufficientPermissions: "&cYou don't have enough permissions to use this command"
    invalidItemType: "&cYou are not allowed to auction this item"
    insufficientBalance: "&cYou don't have enough money to do that"
    noCurrentAuction: "&cThere is no active auction at this time"
    bidOnOwnAuction: "&cYou cannot bid on your own auction"
    alreadyTopBidder: "&cYou are already the top bidder"
    bidTooLow: "&cYour bid was too low"
    bidSyntax: "&cUsage: /auction bid <amount>"
    invalidNumberEntered: "&cPlease enter a valid number"
    notYourAuction: "&cYou aren't able to modify other players auctions"
    currentlyIgnoring: "&cYou can't do that while ignoring auctions"
    notEnoughOfItem: "&cYou don't have enough of that item"
    startSyntax: "&cUsage: /auction start <amount> <price> [increment] [autowin]"
    creativeNotAllowed: "&cYou cannot start auctions while in creative"
    autowinDisabled: "&cPlacing autowin amounts on auctions has been disabled"
    auctionsDisabled: "&cAuctions are currently disabled"
    startPriceTooHigh: "&cYour starting price is too high"
    startPriceTooLow: "&cYour starting price is too low"
    alreadyHaveAuction: "&cYou already have an ongoing auction"
    alreadyInAuctionQueue: "&cYou already have an auction placed in the queue"
    auctionQueueFull: "&cThe auction queue is currently full"
    cantCancelNow: "&cYou can't cancel the auction at this point"
    cantAuctionDamagedItems: "&cYou can't auction damaged items!"
    invalidBidIncrement: "&cYour bid increment was either too high or too low"
    cantUseCommandWhileAuctioning: "&cYou can't use this command while auctioning an item"
    cantUseCommandWhileQueued: "&cYou can't use this command while having an auction queued"
    cantUseCommandWhileTopBidder: "&cYou can't use this command while being the top bidder on an auction"
    cantAuctionNamedItems: "&cYou can't auction off items that have a name"
    cantAuctionBannedLore: "&cYou can't auction off this item as it contains banned lore"
    cantUsePluginInWorld: "&cYou can't use the auctions plugin in this world"
    cantTeleportToDisabledWorld: "&cYou can't teleport into disabled auction worlds while auctioning or participating in an auction"
  # All other messages are just standard messages that are sent to
  # players. These messages have no placeholders available.
  pluginReloaded: "&aThe auctions plugin has been reloaded"
  nowIgnoring: "&6You are now &cignoring &6auction messages"
  noLongerIgnoring: "&6You are no longer ignoring auction messages"
  notEnoughRoom: "&6You didn't have enough room in your inventory so some of your winnings were dropped"
  savedItemReturn: "&6Your auction winnings were saved and have been returned"
  ownerItemReturn: "&6Your items were refunded as nobody bid on your auction"
  auctionsDisabled: "&cAuctions are now disabled, only those with permission can start auctions"
  auctionsEnabled: "&6Auctions have been re-enabled"
  auctionImpounded: "&6The auction was impounded by [player]"
  auctionPlacedInQueue: "&6Your auction has been queued"
  helpMenu:
  - "&6&m----&6[ &eAuction Help Menu &6]&m-----"
  - "&e/auction info &7- &fDisplays current auction information"
  - "&e/auction bid &7<amount> &e- &fBid on an auction"
  - "&e/auction start &7<amount> <price> [increment] [autowin] &7- &fStart an auction"
  - "&e/auction end &7- &fEnds the current auction"
  - "&e/auction cancel &7- &fCancels the current auction"
  - "&e/auction ignore &7- &fIgnore plugin messages"
  - "&e/auction impound &7- &fImpounds the current auctions contents"
  - "&e/auction reload &7- &fReload auction configuration"