# Auction plugin by SainttX

# Configuration options for various plugin integration
# settings can be defined in this section. Each integration
# option has an enable option that tells the plugin whether
# or not the option should be used. Please note that some
# options conflict and may be ignored in certain instances.
integration:
  # Herochat plugin integration options
  # Find the plugin here: http://dev.bukkit.org/bukkit-plugins/herochat/
  herochat:
    enable: true
    # Defines your Herochat chat channel that players must be joined
    # to receive messages from the auction plugin. Messages that
    # are only sent to a single player ignore this and will send no
    # matter what.
    channel: "auction"

# Configuration options for various settings specific to auctions
# ie. times, bid increments, etc.
auctionSettings:
  # How much money users will be charged to start an auction.
  # If a user doesn't have enough money, they will be unable
  # to create an auction. Default: 0.
  startFee: 0
  # The percentage of the winning amount to be removed from
  # the servers economy. For example, if a user wins an auction for
  # $1K and the tax is at 30%, $300 will be removed and the owner
  # of the auction will only be given $700 as a result. Default: 0.
  taxPercent: 0
  # The start time for all auctions. There is currently no
  # way to specify how long your auction should last through commands
  # and as such all auctions will have a duration of this time. This
  # time is configured in seconds and is translated through a utility
  # class to English. For example, if the time is set to 600, the
  # formatter will output '10 minutes'. Default: 30.
  startTime: 30
  # The delay between all auctions in seconds. This is the time
  # between when an auction ends and when a new auction from the queue
  # is started. Auctions that are created within the delay are
  # automatically added to the queue. Default: 5.
  delayBetween: 5
  # The default bid increment to be used when a user doesn't specify
  # their bid increment through commands. For example, if a user types
  # /auction start 1 100, the bid increment will default to this
  # amount. Default: 50.
  defaultBidIncrement: 50
  # The minimum bid increment that is allowed to be specified. Users
  # who attempt to create an auction with an increment that is less
  # than this amount will be denied. Default: 10
  minimumBidIncrement: 10
  # The maximum bid increment that is allowed to be specified. Users
  # who attempt to create an auction with an increment that is greater
  # than this amount will be denied. Default: 9999
  maximumBidIncrement: 9999
  # The minimum amount that is allowed to be defined as an auction start
  # price. Users that attempt to create an auction that fail to meet
  # this criteria will be denied. Default: 0.
  minimumStartPrice: 0
  # The maximum amount that is allowed to be defined as an auction start
  # price. Default: 99999.
  maximumStartPrice: 99999
  # Whether or not players can auction items that have been named through
  # a plugin or anvil. Default: true.
  canAuctionNamedItems: true
  # Whether or not players can auction items that have any durability loss.
  # Default: true.
  canAuctionDamagedItems: true
  # Whether or not players can specify an autowin amount in their auction.
  # If users specify an autowin and this is set to false, they will be
  # denied the creation of the auction. Default: true.
  canSpecifyAutowin: true
  # Whether or not players can auction while in creative mode. Default: false.
  canAuctionInCreative: false
  # Whether or not players can use the /bid command with no arguments. If
  # this is set to true, players can type "/bid" and automatically increment
  # the auction with the auctions bid increment. When set to false, players
  # will be required to specify a bid amount. Default: true.
  canBidAutomatically: true
  # The maximum amount of auctions that are allowed inside an auction. Users
  # who attempt to create auctions when the queue is full will be denied.
  # Default: 3.
  auctionQueueLimit: 3
  # Defines the last time, in seconds, that users are allowed to use
  # the "/auction cancel" command. If an auctions time is less than
  # what is defined here, users will not be able to cancel their auction
  # anymore. Default: 15.
  mustCancelBefore: 15
  # Various settings regarding auction anti sniping can be defined here.
  antiSnipe:
    # Whether or not anti sniping is enabled. Default: true.
    enable: true
    # The time left, in seconds, in an auction that anti-snipe can
    # be enabled at. For example, if set to 3 and a player places a bid
    # at 2 seconds, anti-snipe will trigger if enabled and add
    # 'auctionSettings.antiSnipe.addSeconds' seconds to the auction time.
    # Default: 3.
    timeThreshold: 3
    # The maximum amount of times an auction can be sniped, this is
    # primarily to prevent auctions for going on for indefinite
    # amount of times. Default: 3.
    maxPerAuction: 3
    # The amount of seconds to add whenever an auction is sniped.
    # Default: 5.
    addSeconds: 5

# Various settings unrelated to auction specific options are found in this
# section.
general:
  # Whether or not to shorten times that are formatted through the utility
  # class. For example, this is the difference between times being shown as
  # "5 minutes 5 seconds" vs. "5m, 5s". Default: false.
  shortenedTimeFormat: false
  # A list of worlds that the auction plugin is disabled in. World names
  # are all case sensitive.
  disabledWorlds:
  - "testworld"
  # Various settings settings to block commands found in 'general.blockedCommands'
  # on specific occasions.
  blockCommands:
    # This option will block commands when players are the auction owner.
    # Default: false.
    ifAuctioning: false
    # This option will block commands when players have an auction in the
    # queue. Default: false.
    ifQueued: false
    # This option will block commands when players are the top bidder.
    # Default: false.
    ifTopBidder: false
  # A list of commands that are blocked if any of the settings in
  # 'general.blockCommands.*' are set to true. Commands here should
  # be defined as the players type them. For example, if a player
  # types /test hello, it will match the command '/test'. Keep in
  # mind that all commands are formatted to be all lower cases, so
  # commands entered here should be in all lower case.
  blockedCommands:
  - "/test"
  # A list of Bukkit Materials that are not allowed to be auctioned.
  # Valid materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  blockedMaterials:
  - "BEDROCK"
  # A list of lores that are not allowed to be present inside any
  # lore strings on an item. For example, if we have "A string of
  # lore" defined in this list (default) and an item contains
  # the lore strings "hello", "this is lore", and "lol A string of
  # lore" the item will not be allowed to go into auction due to
  # the fact that "A string of lore" is present in the third line.
  blockedLore:
  - "A string of lore"
  # A list of times that the plugin will broadcast the amount
  # of time left in the auction. The format of this list can
  # be specified as it currently is ("["#", "#"]") or as above.
  broadcastTimes: ["60", "30", "10", "3", "2", "1"]

# Enabling and disabling certain features
allow-auction-help-command: true
allow-auction-end-command: false
allow-auction-cancel-command: true