# Auction plugin by SainttX
# Allow multiple auctions running in different worlds
# Message users a simple notice of auctions in other worlds
# will not show bids or end, only start
auction-time: 30
delay-between-auctions-seconds: 5

# Allow/disallow
allow-autowin: true
allow-creative: false
allow-help-command: false
allow-end: false

# Start fee and tax
# If user has auction.tax.exempt, no tax charged
auction-start-fee: 1
auction-tax-percentage: 0

# The minimum amount that player has to outbid by
minimum-bid-increment: 1

# This allows/disallows players using /bid to bid
# the minimum-bid-increment
allow-autobid: true

# Minimum and maximum prices
min-start-price: 10
max-start-price: 100

# Auction queues
queue-limit: 3

# Anti-snipe
# max-per-auction is the max amount of times an auction can have time added
# add-seconds is the amount of time in seconds to add each time the auction is sniped
enable-anti-snipe: true
anti-snipe-max-per-auction: 3
anti-snipe-add-seconds: 5

# Use http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
banned-items:
- BEDROCK